version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: postgres
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: admin
      TYPEORM_PASSWORD: admin
      TYPEORM_DATABASE: admin
      TYPEORM_ENTITIES: dist/**/*.entity.js
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_LOGGING: "true"
    volumes:
      - .:/app

volumes:
  postgres_data:
